<?php
declare(strict_types=1);

/**
 * FormGroupsApi.
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DocuSign\Rooms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DocuSign Rooms API - v2
 *
 * An API for an integrator to access the features of DocuSign Rooms
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DocuSign\Rooms\Api\FormGroupsApi;


class GetFormGroupsOptions
{
    /**
      * $count Number of Form Groups to include in the response, (Default 100).
      * @var ?int
      */
    protected ?int $count = null;

    /**
     * Gets count
     * @return ?int
     */
    public function getCount(): ?int
    {
        return $this->count;
    }

    /**
     * Sets count
     * @param ?int $count Number of Form Groups to include in the response, (Default 100).
     * @return self
     */
    public function setCount(?int $count): self
    {
        $this->count = $count;
        return $this;
    }
    /**
      * $start_position Position in the overall list of Form Groups to begin results.
      * @var ?int
      */
    protected ?int $start_position = null;

    /**
     * Gets start_position
     * @return ?int
     */
    public function getStartPosition(): ?int
    {
        return $this->start_position;
    }

    /**
     * Sets start_position
     * @param ?int $start_position Position in the overall list of Form Groups to begin results.
     * @return self
     */
    public function setStartPosition(?int $start_position): self
    {
        $this->start_position = $start_position;
        return $this;
    }
}



namespace DocuSign\Rooms\Api;

use DocuSign\Rooms\Client\ApiClient;
use DocuSign\Rooms\Client\ApiException;
use DocuSign\Rooms\Configuration;
use DocuSign\Rooms\ObjectSerializer;

/**
 * FormGroupsApi Class Doc Comment
 *
 * @category Class
 * @package  DocuSign\Rooms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FormGroupsApi
{
    /**
     * API Client
     *
     * @var ApiClient instance of the ApiClient
     */
    protected ApiClient $apiClient;

    /**
     * Constructor
     *
     * @param ApiClient|null $apiClient The api client to use
     * @return void
     */
    public function __construct(ApiClient $apiClient = null)
    {
        $this->apiClient = $apiClient ?? new ApiClient();
    }

    /**
     * Get API client
     *
     * @return ApiClient get the API client
     */
    public function getApiClient(): ApiClient
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param ApiClient $apiClient set the API client
     *
     * @return self
     */
    public function setApiClient(ApiClient $apiClient): self
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
    * Update $resourcePath with $
    *
    * @param string $resourcePath
    * @param string $baseName
    * @param string $paramName
    *
    * @return string
    */
    public function updateResourcePath(string $resourcePath, string $baseName, string $paramName): string
    {
        return str_replace(
            "{" . $baseName . "}",
            $this->apiClient->getSerializer()->toPathValue($paramName),
            $resourcePath
        );
    }


    /**
     * Operation assignFormGroupForm
     *
     * Assigns a form to a form group.
     *
     * @param ?string $form_group_id 
     * @param ?string $account_id 
     * @param \DocuSign\Rooms\Model\FormGroupFormToAssign $body  (optional)
     * @throws ApiException on non-2xx response
     * @return \DocuSign\Rooms\Model\FormGroupFormToAssign
     */
    public function assignFormGroupForm($form_group_id, $account_id, $body = null): \DocuSign\Rooms\Model\FormGroupFormToAssign
    {
        list($response) = $this->assignFormGroupFormWithHttpInfo($form_group_id, $account_id, $body);
        return $response;
    }

    /**
     * Operation assignFormGroupFormWithHttpInfo
     *
     * Assigns a form to a form group.
     *
     * @param ?string $form_group_id 
     * @param ?string $account_id 
     * @param \DocuSign\Rooms\Model\FormGroupFormToAssign $body  (optional)
     * @throws ApiException on non-2xx response
     * @return array of \DocuSign\Rooms\Model\FormGroupFormToAssign, HTTP status code, HTTP response headers (array of strings)
     */
    public function assignFormGroupFormWithHttpInfo($form_group_id, $account_id, $body = null): array
    {
        // verify the required parameter 'form_group_id' is set
        if ($form_group_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $form_group_id when calling assignFormGroupForm');
        }
        // verify the required parameter 'account_id' is set
        if ($account_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $account_id when calling assignFormGroupForm');
        }
        // parse inputs
        $resourcePath = "/v2/accounts/{accountId}/form_groups/{formGroupId}/assign_form";
        $httpBody = $_tempBody ?? ''; // $_tempBody is the method argument, if present
        $queryParams = $headerParams = $formParams = [];
        $headerParams['Accept'] ??= $this->apiClient->selectHeaderAccept(['text/plain', 'application/json', 'text/json']);
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json-patch+json', 'application/json', 'text/json', 'application/_*+json']);


        // path params
        if ($form_group_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "formGroupId", $form_group_id);
        }
        // path params
        if ($account_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "accountId", $account_id);
        }

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\DocuSign\Rooms\Model\FormGroupFormToAssign',
                '/v2/accounts/{accountId}/form_groups/{formGroupId}/assign_form'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\DocuSign\Rooms\Model\FormGroupFormToAssign', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 204:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\FormGroupFormToAssign', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation createFormGroup
     *
     * Creates a form group.
     *
     * @param ?string $account_id 
     * @param \DocuSign\Rooms\Model\FormGroupForCreate $body  (optional)
     * @throws ApiException on non-2xx response
     * @return \DocuSign\Rooms\Model\FormGroup
     */
    public function createFormGroup($account_id, $body = null): \DocuSign\Rooms\Model\FormGroup
    {
        list($response) = $this->createFormGroupWithHttpInfo($account_id, $body);
        return $response;
    }

    /**
     * Operation createFormGroupWithHttpInfo
     *
     * Creates a form group.
     *
     * @param ?string $account_id 
     * @param \DocuSign\Rooms\Model\FormGroupForCreate $body  (optional)
     * @throws ApiException on non-2xx response
     * @return array of \DocuSign\Rooms\Model\FormGroup, HTTP status code, HTTP response headers (array of strings)
     */
    public function createFormGroupWithHttpInfo($account_id, $body = null): array
    {
        // verify the required parameter 'account_id' is set
        if ($account_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $account_id when calling createFormGroup');
        }
        // parse inputs
        $resourcePath = "/v2/accounts/{accountId}/form_groups";
        $httpBody = $_tempBody ?? ''; // $_tempBody is the method argument, if present
        $queryParams = $headerParams = $formParams = [];
        $headerParams['Accept'] ??= $this->apiClient->selectHeaderAccept(['text/plain', 'application/json', 'text/json']);
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json-patch+json', 'application/json', 'text/json', 'application/_*+json']);


        // path params
        if ($account_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "accountId", $account_id);
        }

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\DocuSign\Rooms\Model\FormGroup',
                '/v2/accounts/{accountId}/form_groups'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\DocuSign\Rooms\Model\FormGroup', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\FormGroup', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation deleteFormGroup
     *
     * Deletes a form group.
     *
     * @param ?string $form_group_id 
     * @param ?string $account_id 
     * @throws ApiException on non-2xx response
     * @return mixed
     */
    public function deleteFormGroup($form_group_id, $account_id): mixed
    {
        list($response) = $this->deleteFormGroupWithHttpInfo($form_group_id, $account_id);
        return $response;
    }

    /**
     * Operation deleteFormGroupWithHttpInfo
     *
     * Deletes a form group.
     *
     * @param ?string $form_group_id 
     * @param ?string $account_id 
     * @throws ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteFormGroupWithHttpInfo($form_group_id, $account_id): array
    {
        // verify the required parameter 'form_group_id' is set
        if ($form_group_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $form_group_id when calling deleteFormGroup');
        }
        // verify the required parameter 'account_id' is set
        if ($account_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $account_id when calling deleteFormGroup');
        }
        // parse inputs
        $resourcePath = "/v2/accounts/{accountId}/form_groups/{formGroupId}";
        $httpBody = $_tempBody ?? ''; // $_tempBody is the method argument, if present
        $queryParams = $headerParams = $formParams = [];
        $headerParams['Accept'] ??= $this->apiClient->selectHeaderAccept(['text/plain', 'application/json', 'text/json']);
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType([]);


        // path params
        if ($form_group_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "formGroupId", $form_group_id);
        }
        // path params
        if ($account_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "accountId", $account_id);
        }

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'DELETE',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/v2/accounts/{accountId}/form_groups/{formGroupId}'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation getFormGroup
     *
     * Gets a form group.
     *
     * @param ?string $form_group_id 
     * @param ?string $account_id 
     * @throws ApiException on non-2xx response
     * @return \DocuSign\Rooms\Model\FormGroup
     */
    public function getFormGroup($form_group_id, $account_id): \DocuSign\Rooms\Model\FormGroup
    {
        list($response) = $this->getFormGroupWithHttpInfo($form_group_id, $account_id);
        return $response;
    }

    /**
     * Operation getFormGroupWithHttpInfo
     *
     * Gets a form group.
     *
     * @param ?string $form_group_id 
     * @param ?string $account_id 
     * @throws ApiException on non-2xx response
     * @return array of \DocuSign\Rooms\Model\FormGroup, HTTP status code, HTTP response headers (array of strings)
     */
    public function getFormGroupWithHttpInfo($form_group_id, $account_id): array
    {
        // verify the required parameter 'form_group_id' is set
        if ($form_group_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $form_group_id when calling getFormGroup');
        }
        // verify the required parameter 'account_id' is set
        if ($account_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $account_id when calling getFormGroup');
        }
        // parse inputs
        $resourcePath = "/v2/accounts/{accountId}/form_groups/{formGroupId}";
        $httpBody = $_tempBody ?? ''; // $_tempBody is the method argument, if present
        $queryParams = $headerParams = $formParams = [];
        $headerParams['Accept'] ??= $this->apiClient->selectHeaderAccept(['text/plain', 'application/json', 'text/json']);
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType([]);


        // path params
        if ($form_group_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "formGroupId", $form_group_id);
        }
        // path params
        if ($account_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "accountId", $account_id);
        }

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\DocuSign\Rooms\Model\FormGroup',
                '/v2/accounts/{accountId}/form_groups/{formGroupId}'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\DocuSign\Rooms\Model\FormGroup', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\FormGroup', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation getFormGroups
     *
     * Get account Form Groups.
     *
     * @param ?string $account_id 
     * @param  \DocuSign\Rooms\Api\FormGroupsApi\GetFormGroupsOptions for modifying the behavior of the function. (optional)
     * @throws ApiException on non-2xx response
     * @return \DocuSign\Rooms\Model\FormGroupSummaryList
     */
    public function getFormGroups($account_id, \DocuSign\Rooms\Api\FormGroupsApi\GetFormGroupsOptions $options = null): \DocuSign\Rooms\Model\FormGroupSummaryList
    {
        list($response) = $this->getFormGroupsWithHttpInfo($account_id, $options);
        return $response;
    }

    /**
     * Operation getFormGroupsWithHttpInfo
     *
     * Get account Form Groups.
     *
     * @param ?string $account_id 
     * @param  \DocuSign\Rooms\Api\FormGroupsApi\GetFormGroupsOptions for modifying the behavior of the function. (optional)
     * @throws ApiException on non-2xx response
     * @return array of \DocuSign\Rooms\Model\FormGroupSummaryList, HTTP status code, HTTP response headers (array of strings)
     */
    public function getFormGroupsWithHttpInfo($account_id, \DocuSign\Rooms\Api\FormGroupsApi\GetFormGroupsOptions $options = null): array
    {
        // verify the required parameter 'account_id' is set
        if ($account_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $account_id when calling getFormGroups');
        }
        // parse inputs
        $resourcePath = "/v2/accounts/{accountId}/form_groups";
        $httpBody = $_tempBody ?? ''; // $_tempBody is the method argument, if present
        $queryParams = $headerParams = $formParams = [];
        $headerParams['Accept'] ??= $this->apiClient->selectHeaderAccept(['text/plain', 'application/json', 'text/json']);
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType([]);

        if ($options != null)
        {
            // query params
            if ($options->getCount() != 'null') {
                $queryParams['count'] = $this->apiClient->getSerializer()->toQueryValue($options->getCount());
            }
            if ($options->getStartPosition() != 'null') {
                $queryParams['startPosition'] = $this->apiClient->getSerializer()->toQueryValue($options->getStartPosition());
            }
        }

        // path params
        if ($account_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "accountId", $account_id);
        }

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\DocuSign\Rooms\Model\FormGroupSummaryList',
                '/v2/accounts/{accountId}/form_groups'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\DocuSign\Rooms\Model\FormGroupSummaryList', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\FormGroupSummaryList', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation grantOfficeAccessToFormGroup
     *
     * Assign office to a form group so the specified office has access to the form group.
     *
     * @param ?string $form_group_id 
     * @param ?int $office_id 
     * @param ?string $account_id 
     * @throws ApiException on non-2xx response
     * @return mixed
     */
    public function grantOfficeAccessToFormGroup($form_group_id, $office_id, $account_id): mixed
    {
        list($response) = $this->grantOfficeAccessToFormGroupWithHttpInfo($form_group_id, $office_id, $account_id);
        return $response;
    }

    /**
     * Operation grantOfficeAccessToFormGroupWithHttpInfo
     *
     * Assign office to a form group so the specified office has access to the form group.
     *
     * @param ?string $form_group_id 
     * @param ?int $office_id 
     * @param ?string $account_id 
     * @throws ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function grantOfficeAccessToFormGroupWithHttpInfo($form_group_id, $office_id, $account_id): array
    {
        // verify the required parameter 'form_group_id' is set
        if ($form_group_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $form_group_id when calling grantOfficeAccessToFormGroup');
        }
        // verify the required parameter 'office_id' is set
        if ($office_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $office_id when calling grantOfficeAccessToFormGroup');
        }
        // verify the required parameter 'account_id' is set
        if ($account_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $account_id when calling grantOfficeAccessToFormGroup');
        }
        // parse inputs
        $resourcePath = "/v2/accounts/{accountId}/form_groups/{formGroupId}/grant_office_access/{officeId}";
        $httpBody = $_tempBody ?? ''; // $_tempBody is the method argument, if present
        $queryParams = $headerParams = $formParams = [];
        $headerParams['Accept'] ??= $this->apiClient->selectHeaderAccept(['text/plain', 'application/json', 'text/json']);
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType([]);


        // path params
        if ($form_group_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "formGroupId", $form_group_id);
        }
        // path params
        if ($office_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "officeId", $office_id);
        }
        // path params
        if ($account_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "accountId", $account_id);
        }

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/v2/accounts/{accountId}/form_groups/{formGroupId}/grant_office_access/{officeId}'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation removeFormGroupForm
     *
     * Removes a form from a form group.
     *
     * @param ?string $form_group_id 
     * @param ?string $form_id 
     * @param ?string $account_id 
     * @throws ApiException on non-2xx response
     * @return mixed
     */
    public function removeFormGroupForm($form_group_id, $form_id, $account_id): mixed
    {
        list($response) = $this->removeFormGroupFormWithHttpInfo($form_group_id, $form_id, $account_id);
        return $response;
    }

    /**
     * Operation removeFormGroupFormWithHttpInfo
     *
     * Removes a form from a form group.
     *
     * @param ?string $form_group_id 
     * @param ?string $form_id 
     * @param ?string $account_id 
     * @throws ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function removeFormGroupFormWithHttpInfo($form_group_id, $form_id, $account_id): array
    {
        // verify the required parameter 'form_group_id' is set
        if ($form_group_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $form_group_id when calling removeFormGroupForm');
        }
        // verify the required parameter 'form_id' is set
        if ($form_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $form_id when calling removeFormGroupForm');
        }
        // verify the required parameter 'account_id' is set
        if ($account_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $account_id when calling removeFormGroupForm');
        }
        // parse inputs
        $resourcePath = "/v2/accounts/{accountId}/form_groups/{formGroupId}/unassign_form/{formId}";
        $httpBody = $_tempBody ?? ''; // $_tempBody is the method argument, if present
        $queryParams = $headerParams = $formParams = [];
        $headerParams['Accept'] ??= $this->apiClient->selectHeaderAccept(['text/plain', 'application/json', 'text/json']);
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType([]);


        // path params
        if ($form_group_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "formGroupId", $form_group_id);
        }
        // path params
        if ($form_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "formId", $form_id);
        }
        // path params
        if ($account_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "accountId", $account_id);
        }

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/v2/accounts/{accountId}/form_groups/{formGroupId}/unassign_form/{formId}'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation renameFormGroup
     *
     * Renames a form group.
     *
     * @param ?string $form_group_id 
     * @param ?string $account_id 
     * @param \DocuSign\Rooms\Model\FormGroupForUpdate $body  (optional)
     * @throws ApiException on non-2xx response
     * @return \DocuSign\Rooms\Model\FormGroup
     */
    public function renameFormGroup($form_group_id, $account_id, $body = null): \DocuSign\Rooms\Model\FormGroup
    {
        list($response) = $this->renameFormGroupWithHttpInfo($form_group_id, $account_id, $body);
        return $response;
    }

    /**
     * Operation renameFormGroupWithHttpInfo
     *
     * Renames a form group.
     *
     * @param ?string $form_group_id 
     * @param ?string $account_id 
     * @param \DocuSign\Rooms\Model\FormGroupForUpdate $body  (optional)
     * @throws ApiException on non-2xx response
     * @return array of \DocuSign\Rooms\Model\FormGroup, HTTP status code, HTTP response headers (array of strings)
     */
    public function renameFormGroupWithHttpInfo($form_group_id, $account_id, $body = null): array
    {
        // verify the required parameter 'form_group_id' is set
        if ($form_group_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $form_group_id when calling renameFormGroup');
        }
        // verify the required parameter 'account_id' is set
        if ($account_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $account_id when calling renameFormGroup');
        }
        // parse inputs
        $resourcePath = "/v2/accounts/{accountId}/form_groups/{formGroupId}";
        $httpBody = $_tempBody ?? ''; // $_tempBody is the method argument, if present
        $queryParams = $headerParams = $formParams = [];
        $headerParams['Accept'] ??= $this->apiClient->selectHeaderAccept(['text/plain', 'application/json', 'text/json']);
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json-patch+json', 'application/json', 'text/json', 'application/_*+json']);


        // path params
        if ($form_group_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "formGroupId", $form_group_id);
        }
        // path params
        if ($account_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "accountId", $account_id);
        }

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'PUT',
                $queryParams,
                $httpBody,
                $headerParams,
                '\DocuSign\Rooms\Model\FormGroup',
                '/v2/accounts/{accountId}/form_groups/{formGroupId}'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\DocuSign\Rooms\Model\FormGroup', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\FormGroup', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation revokeOfficeAccessFromFormGroup
     *
     * Remove office to a form group so the specified office doesn't have access to the form group.
     *
     * @param ?string $form_group_id 
     * @param ?int $office_id 
     * @param ?string $account_id 
     * @throws ApiException on non-2xx response
     * @return mixed
     */
    public function revokeOfficeAccessFromFormGroup($form_group_id, $office_id, $account_id): mixed
    {
        list($response) = $this->revokeOfficeAccessFromFormGroupWithHttpInfo($form_group_id, $office_id, $account_id);
        return $response;
    }

    /**
     * Operation revokeOfficeAccessFromFormGroupWithHttpInfo
     *
     * Remove office to a form group so the specified office doesn't have access to the form group.
     *
     * @param ?string $form_group_id 
     * @param ?int $office_id 
     * @param ?string $account_id 
     * @throws ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function revokeOfficeAccessFromFormGroupWithHttpInfo($form_group_id, $office_id, $account_id): array
    {
        // verify the required parameter 'form_group_id' is set
        if ($form_group_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $form_group_id when calling revokeOfficeAccessFromFormGroup');
        }
        // verify the required parameter 'office_id' is set
        if ($office_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $office_id when calling revokeOfficeAccessFromFormGroup');
        }
        // verify the required parameter 'account_id' is set
        if ($account_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $account_id when calling revokeOfficeAccessFromFormGroup');
        }
        // parse inputs
        $resourcePath = "/v2/accounts/{accountId}/form_groups/{formGroupId}/revoke_office_access/{officeId}";
        $httpBody = $_tempBody ?? ''; // $_tempBody is the method argument, if present
        $queryParams = $headerParams = $formParams = [];
        $headerParams['Accept'] ??= $this->apiClient->selectHeaderAccept(['text/plain', 'application/json', 'text/json']);
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType([]);


        // path params
        if ($form_group_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "formGroupId", $form_group_id);
        }
        // path params
        if ($office_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "officeId", $office_id);
        }
        // path params
        if ($account_id !== null) {
            $resourcePath = self::updateResourcePath($resourcePath, "accountId", $account_id);
        }

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires OAuth (access token)
        if (strlen($this->apiClient->getConfig()->getAccessToken()) !== 0) {
            $headerParams['Authorization'] = 'Bearer ' . $this->apiClient->getConfig()->getAccessToken();
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/v2/accounts/{accountId}/form_groups/{formGroupId}/revoke_office_access/{officeId}'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\DocuSign\Rooms\Model\ApiError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
}
